CREATE TABLE T(A INT PRIMARY KEY, B INT);
CREATE TABLE S(A INT, B INT, PRIMARY KEY (A, B));
CREATE OR REPLACE TABLE T(A INT CANDIDATE KEY, B INT);
CREATE OR REPLACE TABLE S(A INT, B INT, CANDIDATE KEY (A, B));
CREATE OR REPLACE TABLE T(A INT PRIMARY KEY, B STRING DETERMINED BY A);
CREATE TABLE t (a INT PRIMARY KEY, b INT, c INT);
CREATE TABLE u (a INT, b INT, c INT);


SELECT A FROM T GROUP BY A;
SELECT A, B FROM S GROUP BY A, B;
SELECT A FROM T GROUP BY A;
SELECT A, B FROM S GROUP BY A, B;
SELECT A, B FROM T GROUP BY A, B;
SELECT a, COUNT(*) FROM t GROUP BY a;  -- a es PRIMARY KEY, cada grupo = 1 fila
SELECT a, MAX(b) FROM t GROUP BY a;    -- innecesario: solo 1 fila por grupo

SELECT a, COUNT(*) FROM u GROUP BY a;  -- sin restricciones, puede haber múltiples por grupo
SELECT a, MAX(b) FROM u GROUP BY a;    -- no hay garantía de unicidad
SELECT b, COUNT(*) FROM t GROUP BY b;  -- b no es único, se justifica agrupar
SELECT c, SUM(b) FROM u GROUP BY c;    -- agrupación válida
