CREATE TABLE t (a INT, b INT, c INT); 
CREATE TABLE s (a INT, b INT, c INT); 
CREATE TABLE u (a INT, b INT); 
CREATE TABLE v (a INT, b INT, c INT);

SELECT * FROM t WHERE EXISTS (SELECT 1 FROM s GROUP BY b);
SELECT * FROM t WHERE EXISTS (SELECT * FROM s WHERE s.a = t.a GROUP BY s.b);
SELECT * FROM t WHERE EXISTS (SELECT 1 FROM s WHERE s.a = t.a GROUP BY s.c);
SELECT * FROM t WHERE EXISTS (SELECT 1 FROM s WHERE s.b = t.b GROUP BY s.a);
SELECT * FROM t WHERE EXISTS (SELECT 1 FROM s JOIN u ON u.a = s.a WHERE t.b = s.b GROUP BY s.a);

SELECT * FROM t WHERE EXISTS (SELECT 1 FROM s WHERE s.a = t.a GROUP BY s.a HAVING COUNT(*) > 1);
SELECT a, COUNT(*) FROM t GROUP BY a;



